### PR TITLE
Bug #117018 When the response is set to accept XML, and the response …

### PR DESCRIPTION
**Pull request by twsvaishali**
…has an array with the numric indexes, response is broken

### CODE REVIEW

**Comment by sushan05** [comment]
@twsvaishali , @coolbung , @thite-amol  - I have tested this PR for GET and POST request by setting `Accept` header as `application/xml` and I am **getting the response as expected**.

**Comment by coolbung** [comment]
Can you also comment on whether this is the right approach ?


What about alphanumeric strings starting with numbers for example


On Sat, Jan 06, 2018 at 3:04pm, sushan05 < notifications@github.com [notifications@github.com] > wrote:
@twsvaishali [https://github.com/twsvaishali] , @coolbung [https://github.com/coolbung] , @thite-amol [https://github.com/thite-amol] - I have tested this PR for GET and POST request by setting Accept header as application/xml and I am getting the response as expected .

**Comment by twsvaishali** [comment]
XML breaks if index starts with numbers or some special characters

**Comment by coolbung** [comment]
I want you to comment on the 2 points that I added, especially @sushan05 @thite-amol

**Comment by coolbung** [comment]
This needs a closure @twsvaishali please update the code to address to ensure any kind of keys will work in XML. I suggest you use some method to make the key 'safe' to be used as a XML node before prefixing with 'node_'

**Pull request merged**
